# Generated by Django 4.0.4 on 2022-05-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='registered',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_registered',
            field=models.BooleanField(default=True),
        ),
    ]
