# Generated by Django 4.0.4 on 2022-05-29 18:39

from django.db import migrations, models
import django.db.models.deletion
import ticket.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=220)),
                ('company', models.CharField(max_length=220)),
                ('departure', models.CharField(max_length=220)),
                ('destination', models.CharField(max_length=220)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('count', models.IntegerField(validators=[ticket.validators.validate_count])),
                ('type', models.IntegerField(choices=[(0, 'Bus'), (1, 'Train'), (2, 'Airplane')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, null=True, validators=[ticket.validators.validate_price])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(blank=True, null=True, validators=[ticket.validators.validate_count])),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[ticket.validators.validate_price])),
                ('state', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Canceled'), (2, 'Completed')], default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='ticket.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
