# Generated by Django 4.0.4 on 2022-05-22 03:13

from django.db import migrations, models
import django.db.models.deletion
import ticket.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('name', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=220)),
                ('departure', models.CharField(max_length=220)),
                ('destination', models.CharField(max_length=220)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ticket_number', models.UUIDField(default=uuid.UUID('47affcdf-6ae5-4545-bd3f-5b1cd78cb682'), editable=False)),
                ('count', models.PositiveIntegerField()),
                ('type', models.IntegerField(choices=[(0, 'Bus'), (1, 'Train'), (2, 'Airplane')], default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='ticket.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
