# Generated by Django 4.0.4 on 2022-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_time',
            field=models.DateField(),
        ),
    ]
