# Generated by Django 4.0.4 on 2022-05-22 03:14

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=220, validators=[django.core.validators.RegexValidator(code='invalid_format', message='phone number must be in iranian format', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.UUIDField(default=uuid.UUID('7f2a5f54-2f59-4e7b-b2c9-958607bd3e9f'), editable=False),
        ),
    ]
