# Generated by Django 4.0.4 on 2022-05-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_order_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tickets',
            new_name='ticket',
        ),
    ]
