# Generated by Django 4.0.4 on 2022-05-22 03:23

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=220, validators=[django.core.validators.RegexValidator(code='invalid_format', message='phone number must be in iranian format', regex='^\\+989\\d{9}$|^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.UUIDField(default=uuid.UUID('128813ea-7370-4d74-a7a1-f3a84e0fcb6c'), editable=False),
        ),
    ]
