# Generated by Django 4.0.4 on 2022-05-22 14:38

from django.db import migrations, models
import ticket.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_company_phone_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True, validators=[ticket.validators.validate_price]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='count',
            field=models.IntegerField(validators=[ticket.validators.validate_count]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.UUIDField(default=uuid.UUID('b4812cd5-69e5-4641-b2be-5c1530d548ee'), editable=False),
        ),
    ]
