# Generated by Django 4.0.4 on 2022-05-22 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_price_alter_ticket_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.UUIDField(default=uuid.UUID('6b2ee425-069d-4465-af0a-cce1697b7df9'), editable=False),
        ),
    ]
