# Generated by Django 4.0.4 on 2022-05-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_company_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_number',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.CharField(max_length=220),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
